###########################################
# Ubuntu server
---

server_timezone: "Europe/Kiev"
journal_vacuum_size: "500M"
journal_vacuum_time: "90d"
server_base_apps:
  - vim
  - ranger
  - git
  - screen
  - htop

server_allowed_access:
#  test:
#    action: allow
#    interface: eth0
#    direction: in
#    proto: udp
#    src: 1.2.3.5
#    from_port: 5469
#    dest: 1.2.3.4
#    to_port: 5469

  - action: allow
    interface: eth0
    direction: in
    proto: udp
    src: 1.2.3.5
    from_port: 5469
    dest: 1.2.3.4
    to_port: 5469

server_logrotate_conf:
  - name: test
    file_name: /var/log/test-app/*.log
    params:
      - "daily"
      - "missingok"
      - "rotate 14"
      - "compress"
      - "notifempty"
      - "create 0640 www-data www-data"
      - "sharedscripts"
      - "postrotate"
      - "systemctl reload test-app"
      - "endscript"
