###############################################################################
# Ubuntu server
---

server_name: spec-server-2
server_timezone: "Europe/Kiev"
server_admin_email: klimenkomaximsergievich@gmail.com
journal_vacuum_size: "500M"
journal_vacuum_time: "90d"
server_apps:
  - name: dnsutils
    state: present
  - name: net-tools
    state: present
  - name: rkhunter
    state: present
  - name: curl
    state: present
  - name: wget
    state: present
  - name: vim
    state: present
  - name: ranger
    state: present
  - name: git
    state: present
  - name: screen
    state: present
  - name: htop
    state: present
  - name: screen
    state: present
  - name: hping3
    state: present

server_securetty_content: |
  #tty1
  #tty2
  #tty3
  #tty4
  #tty5
  #tty6
  #tty7
  #tty8

server_allowed_access:
  - action: deny
    interface: eth0
    direction: in
    proto: udp
    src: 1.2.3.5
    from_port: 5469
    dest: 1.2.3.4
    to_port: 5469
    route: no

server_logrotate_conf:
  - name: test
    file_name: /var/log/test-app/*.log
    params:
      - "daily"
      - "missingok"
      - "rotate 14"
      - "compress"
      - "notifempty"
      - "create 0640 www-data www-data"
      - "sharedscripts"
      - "postrotate"
      - "systemctl reload test-app"
      - "endscript"

server_megumin_attack: false
script_content: |
          #!/usr/bin/env bash
          # all humans will be health
