---
# tasks file for boinc
- debug:
    var: "{{ inventory_hostname }}"

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - gst-plugins-bad-libs
    - boinc
    - boinctui
  when: ansible_distribution == 'Archlinux'
  tags:
    - install_boinc_packages

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - boinc-client
    - boinctui
  when: ansible_distribution == 'Ubuntu'
  tags:
    - install_boinc_packages

- name: Enable boinc service
  shell: sudo systemctl enable boinc-client.service
  tags:
    - install_boinc_packages

- name: Start boinc service
  service:
    name: boinc-client.service
    state: started
  tags:
    - install_boinc_packages
