---
# tasks file for boinc

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - boinc-client
    - boinctui
  register: virtualbox_install
  tags:
    - install_packages

- name: Enable boinc service
  shell: sudo systemctl enable boinc-client.service
  tags:
    - install_packages

- name: Start boinc service
  service:
    name: boinc-client.service
    state: started
  tags:
    - install_packages
