---

- name: Update pacman keyring | Arch
  shell: |
    pacman-key --init &&
    pacman-key --populate
  become: true
  become_user: root
  tags:
    - prometheus
    - reboot_machine  

- name: Update pacman database | Arch
  shell: sudo pacman -Sy
  tags:
    - prometheus
    - reboot_machine  

- name: Install prometheus | Arch
  pacman:
    pkg: '{{ item }}'
    update_cache: yes
    state: latest
  with_items:
    - prometheus
    - alertmanager
  tags:
    - prometheus

- name: Install prometheus exporters | Arch
  pacman:
    pkg: '{{ item }}'
    update_cache: yes
    state: latest
  with_items:
    - prometheus-node-exporter
#    - prometheus-process-exporter-bin
    - prometheus-systemd-exporter
    - prometheus-wireguard-exporter
#    - prometheus-nginxlog-exporter-bin
    - nginx-prometheus-exporter
  tags:
    - prometheus
