---
# tasks file for ansible/roles/prometheus
- debug:
    var: "{{ inventory_hostname }}"

- name: Print all available facts
  debug:
    var: ansible_facts

- name: Install Ubuntu/Debian packages and configure OS specific settings
  include_tasks: debbased.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install Arch packages and configure OS specific settings
  include_tasks: archlinux.yml
  when: ansible_distribution == 'Archlinux'
