---
- name: Install Nginx and system utils | Arch
  pacman:
    pkg: '{{ item }}'
    update_cache: yes
    state: latest
  with_items:
    - nginx
    - certbot
  tags:
    - instal_nginx

- name: Create SSL/TLS sertifiate for Nginx by using LetsEncrypt | Arch
  shell: sudo systemctl stop nginx && sudo killall nginx
  ignore_errors: true
  tags:
    - instal_nginx
