---
# tasks file for roles/nginx

- name: Added key for Nginx
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: ABF5BD827BD9BF62
  tags:
    - add_repository

- name: Added Ubuntu Nginx repository
  apt_repository:
    repo: deb https://nginx.org/packages/ubuntu/ "{{ ansible_distribution_release }}" nginx
    state: present
  tags:
    - add_repository

- name: Download Nginx key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 7BF576066ADA65728FC7E70A8C47BE8E75BCA694
  tags:
    - add_repository

- name: Added Ubuntu Certbot repository
  apt_repository:
    repo: deb https://ppa.launchpadcontent.net/certbot/certbot/ubuntu bionic main
    state: present
  tags:
    - add_repository

- name: Install Nginx package
  apt:
    name: nginx
    state: present
  tags:
    - add_nginx

- name: Install Nginx package
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - certbot
    - python-certbot-nginx
  tags:
    - add_nginx

- name: Create directory for site configs
  file:
    dest: /etc/nginx/sites-enabled
    state: directory
  tags:
    - add_nginx

- name: Create directory for site data
  file:
    dest: /var/www
    state: directory
    owner: nginx
  tags:
    - add_nginx

- name: Create main config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    force: yes
  tags:
    - add_nginx

- name: Create Letsencrypt dir
  file:
    dest: /etc/letsencrypt/live/
    state: directory
  tags:
    - add_nginx
    - configure

- name: Create ssl certificate
  shell: sudo certbot certonly --nginx -n -m {{ server_admin_email }} --agree-tos -d {{ server_name }}
  tags:
    - add_nginx
    - configure

- name: Install Nginx default site
  template:
    src: "{{ item }}"
    dest: /etc/nginx/sites-enabled/{{ item | basename | regex_replace('\.j2$', '') }}
    force: yes
  with_items:
    - "{{ lookup('fileglob', '{{role_path}}/templates/*.site.conf.j2', wantlist=True) }}"
  tags:
    - add_nginx
    - configure

- name: Create test site dir
  file:
    dest: "{{ server_root_folder }}"
    state: directory
    recurse: yes
    owner: nginx
    group: nginx
    mode: 0755
  tags:
    - add_nginx
    - configure

- name: Added test site code
  copy:
    src: index.html
    dest: "{{ server_root_folder }}/index.html"
    owner: nginx
    group: nginx
    mode: 0644
  tags:
    - add_nginx
    - configure

- name: Validate config
  shell: sudo killall nginx && sudo nginx -t
  notify: "restart nginx service"
  tags:
    - add_nginx
    - configure

43
80 
83 
84 
85 
89 
110
143
443
465
587
700
993
995
1084
1085
1089
1443
1935
3389
5222
5432
5900
5901
5999
8080
8081
8085
8086
8088
8089
8090
8099
9100
9200
20000
30000
