---
# tasks file for roles/nginx

- name: Added key for Nginx
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: ABF5BD827BD9BF62
  tags:
    - add_repository

- name: Added Ubuntu Nginx repository
  apt_repository:
    repo: deb https://nginx.org/packages/ubuntu/ "{{ ansible_distribution_release }}" nginx
    state: present
  tags:
    - add_repository

- name: Install Nginx package
  apt:
    name: nginx
    state: present
  tags:
    - add_nginx

- name: Configure Nginx
