---
# tasks file for roles/nginx

- name: Added key for Nginx
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: ABF5BD827BD9BF62
  tags:
    - add_repository

- name: Added Ubuntu Nginx repository
  apt_repository:
    repo: deb https://nginx.org/packages/ubuntu/ "{{ ansible_distribution_release }}" nginx
    state: present
  tags:
    - add_repository

- name: Added Ubuntu Certbot repository
  apt_repository:
    repo: deb https://ppa.launchpadcontent.net/certbot/certbot/ubuntu bionic main
    state: present
  tags:
    - add_repository

- name: Install Nginx package
  apt:
    name: nginx
    state: present
  tags:
    - add_nginx

- name: Install Nginx package
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - certbot
    - python-certbot-nginx
  tags:
    - add_nginx

- name: Create directory for site configs
  file:
    dest: /etc/nginx/sites-enabled
    state: directory
  tags:
    - add_nginx

- name: Create directory for site data
  file:
    dest: /var/www
    state: directory
    owner: nginx
  tags:
    - add_nginx

- name: Create main config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    force: yes
  tags:
    - add_nginx

- name: Install Nginx default site
  template:
    src: "{{ item }}"
    dest: /etc/nginx/sites-enabled/{{ item | basename | regex_replace('\.j2$', '') }}
    force: yes
  with_items:
    - "{{ lookup('fileglob', '{{role_path}}/templates/*.site.conf.j2', wantlist=True) }}"
  tags:
    - add_nginx
    - configure

- name: Create ssl certificate
  shell: sudo certbot certonly --nginx -n -m {{ server_admin_email }} --agree-tos -d {{ server_name }}
  tags:
    - add_nginx
    - configure

- name: Validate config
  shell: sudo nginx -t
  notify: "restart nginx service"
  tags:
    - add_nginx
    - configure

