---
#- hosts: all
- hosts: uni_server

  roles:
    - name: server_config
      become: yes
      become_user: root
      tags: configure

- hosts: uni_server

  roles:
    - name: nginx
      become: yes
      become_user: root
      tags: nginx
