#######################################################################
# Openvpn
---

- name: Install Wireguard package
  apt:
    name: "{{ item  }}"
    state: present
  with_items:
    - wireguard
  tags:
    - add_wireguard

#
#    ip address add dev wg0 192.168.3.1/24
#    ip address add dev wg0 192.168.3.1 peer 192.168.3.2
#

- debug:
    msg: "{{ wireguard_network_cidr | ipaddr('net') | ipaddr('0') }}"

- debug:
    msg: "{{ wireguard_network_cidr | ipaddr('net') | ipaddr('1') }}"

#- name: Create Interface
#  shell: |
#    ip link add dev wg0 type wireguard
#    ip address add dev wg0 {{ wireguard_network_cidr }}
#    ip address add dev wg0 {{ wireguard_network_cidr | ipaddr('net') | ipaddr('0') | ipv4('address') }} peer {{ wireguard_network_cidr | ipaddr('net') | ipaddr('1') | ipv4('address') }}
    # 192.168.3.2
#    wg genkey > privatekey
#    wg genpsk > presharedkey
#    wg set wg0 listen-port {{ wireguard_port }} private-key privatekey peer $(cat privatekey | wg pubkey) allowed-ips 0.0.0.0/0 endpoint {{ ansible_host }}:{{ wireguard_port }}

